# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
permalink: /:year/:month/:day/:title.html
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Poarry的博客

description: Stay hungry,Stay foolish.
# gavatar头像及favicon
gavatar: /assets/ico/avatar.png
favicon: /assets/ico/avatar.png

author:
  name: Poarry
  github: Poarry
  weibo: 波波_1936
  wechat: xy_zlf
  qq: 719151128
  email: 719151128@qq.com

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: 
HOST: http://xyzlf.github.io

excerpt_separator: <!--more-->

gems: [jekyll-paginate]